version: "3"

services:
  server:
    container_name: server
    build:
       context: ./server
       dockerfile: Dockerfile
    command: npm run dev    
    ports:
      - '5000:5000'
    working_dir: /usr/src/app
    restart: unless-stopped
  client:
    container_name: client
    restart: always  
    working_dir: /usr/src/app
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '3000:3000' 
  